// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function findIfExists(element, _list) {
  while(true) {
    var list = _list;
    if (!list) {
      return false;
    }
    var head = list.hd;
    if (Caml_obj.caml_equal(head, element)) {
      return true;
    }
    if (Caml_obj.caml_notequal(head, element)) {
      _list = list.tl;
      continue ;
    }
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "patternMatchingReason.re",
            2,
            68
          ],
          Error: new Error()
        };
  };
}

var PatternMatchingExampleReason = {
  findIfExists: findIfExists
};

var does3001Exist = findIfExists(3001, {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: {
            hd: 4,
            tl: {
              hd: 3001,
              tl: /* [] */0
            }
          }
        }
      }
    });

var does27Exist = findIfExists(27, {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: {
            hd: 4,
            tl: /* [] */0
          }
        }
      }
    });

console.log(does3001Exist);

console.log(does27Exist);

exports.PatternMatchingExampleReason = PatternMatchingExampleReason;
exports.does3001Exist = does3001Exist;
exports.does27Exist = does27Exist;
/* does3001Exist Not a pure module */
